# Pytorch basics

In [1]:
from __future__ import print_function
import torch

In [8]:
# Empty/uninitialized tensor
empty = torch.empty(3, 5)
print(empty)
print(empty.size())
print(type(empty))

tensor([[9.9184e-39, 8.7245e-39, 9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38, 1.0469e-38, 4.2246e-39],
        [1.0378e-38, 9.6429e-39, 9.2755e-39, 9.7346e-39, 1.0745e-38]])
torch.Size([3, 5])
<class 'torch.Tensor'>


In [9]:
# Random initialized tensor
rand = torch.rand(3, 5)
print(rand)

tensor([[0.5087, 0.0934, 0.5908, 0.5990, 0.3271],
        [0.0795, 0.9988, 0.8673, 0.9631, 0.1866],
        [0.3281, 0.9466, 0.2076, 0.8620, 0.3736]])


In [11]:
# Zeros initialized tensor
zeros = torch.zeros(3, 5)
print(zeros)

# Zeros initialized tensor of dtype: long
zeros = torch.zeros(3, 5, dtype=torch.long)
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


In [13]:
# Tensor directly from data
x = torch.tensor([[1, 2], [3, 4], [5, 6]]) # long type tensor
print(type(x))
print(x.size())
print(x)

<class 'torch.Tensor'>
torch.Size([3, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [17]:
y = torch.randn(3,2) # Float type tensor
print(y)

tensor([[ 0.2879,  0.4760],
        [-0.7978, -0.1562],
        [ 0.5109,  0.3913]])


In [22]:
# Convert tensor type to float type
x = torch.tensor(x, dtype=torch.float)
print(x)

# Addition operation: types should be same
print(x + y)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1.2879, 2.4760],
        [2.2022, 3.8438],
        [5.5109, 6.3913]])


In [24]:
# Resize/reshape operation
y = torch.rand(4, 4, dtype=torch.float)
print(y)
print(y.size())
z = y.view(16)
print(z)
print(z.size())
w = y.view(-1, 8)
print(w)
print(w.size())

tensor([[0.6599, 0.0633, 0.2725, 0.4203],
        [0.7134, 0.5380, 0.0595, 0.3051],
        [0.6903, 0.7265, 0.3571, 0.0716],
        [0.5102, 0.8022, 0.7786, 0.4034]])
torch.Size([4, 4])
tensor([0.6599, 0.0633, 0.2725, 0.4203, 0.7134, 0.5380, 0.0595, 0.3051, 0.6903,
        0.7265, 0.3571, 0.0716, 0.5102, 0.8022, 0.7786, 0.4034])
torch.Size([16])
tensor([[0.6599, 0.0633, 0.2725, 0.4203, 0.7134, 0.5380, 0.0595, 0.3051],
        [0.6903, 0.7265, 0.3571, 0.0716, 0.5102, 0.8022, 0.7786, 0.4034]])
torch.Size([2, 8])


In [25]:
# Value of item in 1-item tensor
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2330])
0.23301082849502563


In [28]:
# Conversion of Tensor to Numpy array
import numpy as np

rand = torch.rand(3, 5, dtype=torch.float)
print(rand)

arr = rand.numpy()
print(arr)
print(type(arr))
print(arr.shape)

tensor([[0.2100, 0.6967, 0.6107, 0.4805, 0.6297],
        [0.0085, 0.4808, 0.9559, 0.1654, 0.1124],
        [0.0239, 0.7211, 0.6020, 0.9123, 0.1763]])
[[0.21003336 0.6967495  0.61070186 0.48050374 0.62972426]
 [0.00846606 0.48077494 0.95593    0.16544217 0.11238414]
 [0.02394271 0.72105503 0.6019659  0.912349   0.17635   ]]
<class 'numpy.ndarray'>
(3, 5)


In [29]:
# Conversion of Numpy array to Tensor
rand = torch.from_numpy(arr)
print(rand)
print(type(rand))

tensor([[0.2100, 0.6967, 0.6107, 0.4805, 0.6297],
        [0.0085, 0.4808, 0.9559, 0.1654, 0.1124],
        [0.0239, 0.7211, 0.6020, 0.9123, 0.1763]])
<class 'torch.Tensor'>


## Autograd feature

Flow:

1. f1 = x           | x
2. f2 = f1 * 4      | 4x
3. f3 = f2**2       | 16x^2
4. f4 = f3 + f2     | 16x^2 + 4x
5. f5 = f4.sum()    | sum(...)
5. gradient(f5)     | 

In [46]:
x = torch.tensor([2, 4], dtype=torch.float, requires_grad=True)
print(x)

tensor([2., 4.], requires_grad=True)


In [47]:
f1 = x
f2 = f1 * 4
f3 = f2**2
f4 = f3 + f2
f5 = f4.sum()
print(f5)

tensor(344., grad_fn=<SumBackward0>)


In [48]:
f5.backward()
print(x.grad)

tensor([ 68., 132.])


## Numpy vs Pytorch

### Numpy array initialization
+ Create a numpy array
+ Display array
+ Display type of array
+ Display size of array

In [4]:
import numpy as np

array = [[1,2,3],[4,5,6]]
nparray = np.array(array)
print(nparray)
print(type(nparray))
print(nparray.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


### Pytorch Tensor initialization

+ Create a torch.Tensor from array
+ Display Tensor
+ Display type of Tensor
+ Display size of Tensor

In [5]:
import torch

tensor_arr = torch.Tensor(array)
print(tensor_arr)
print(tensor_arr.type)
print(tensor_arr.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
<built-in method type of Tensor object at 0x0000020977D6DBD0>
torch.Size([2, 3])


### Identity array

In [6]:
print(np.ones((2,4)))

print(torch.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Random array

In [8]:
print(np.random.randn(2, 4))
print(np.random.rand(2, 4))

print(torch.randn((2,4)))
print(torch.rand((2,4)))

[[ 0.49757941  1.21899989 -1.97343286 -0.8883544 ]
 [-0.07033942  1.35262783 -1.1313371   0.89954977]]
[[0.52806885 0.69094027 0.68482042 0.77944977]
 [0.15156258 0.27967442 0.67937988 0.01698071]]
tensor([[-0.7756,  0.4732,  0.3204,  0.8793],
        [-0.3951,  0.0433,  1.3193,  0.3694]])
tensor([[0.9402, 0.2392, 0.4254, 0.0728],
        [0.8128, 0.7795, 0.9274, 0.3200]])


### Numpy array to Tensor and vice-versa

In [9]:
rand_arr = np.random.rand(2, 4)
print(rand_arr)
print(type(rand_arr))

np_to_tensor = torch.from_numpy(rand_arr)
print(np_to_tensor)
print(type(np_to_tensor))

tensor_to_np = np_to_tensor.numpy()
print(tensor_to_np)
print(type(tensor_to_np))

[[0.08688301 0.72823945 0.06910246 0.60743097]
 [0.9022125  0.65736611 0.68962442 0.15798959]]
<class 'numpy.ndarray'>
tensor([[0.0869, 0.7282, 0.0691, 0.6074],
        [0.9022, 0.6574, 0.6896, 0.1580]], dtype=torch.float64)
<class 'torch.Tensor'>
[[0.08688301 0.72823945 0.06910246 0.60743097]
 [0.9022125  0.65736611 0.68962442 0.15798959]]
<class 'numpy.ndarray'>


## Variables in pytorch

+ Difference b/w Tensor and Variables? Variables accumulates gradients. 
+ Variables are used for back propogation

In [11]:
from torch.autograd import Variable

var = Variable(torch.ones((3,3)), requires_grad = True)
print(var)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


### Basics of backward propogation

+ Let an equation be $y = x^2$
+ $X = [2, 4]$
+ Let recap o equation be $o = \frac{1}{2}\sum y = \frac{1}{2}\sum x^2$
+ Derivative of $o = x$ therefore, gradients $ = [2, 4]$

In [14]:
x = Variable(torch.Tensor([2, 4]), requires_grad = True)
y = x**2
print(y)

o = (1/2) * sum(y)
print(o)

o.backward() # Back Propogation

print('Gradients: {}'.format(x.grad))

tensor([ 4., 16.], grad_fn=<PowBackward0>)
tensor(10., grad_fn=<MulBackward0>)
Gradients: tensor([2., 4.])
