# Pytorch basics

## Numpy vs Pytorch

### Numpy array initialization
+ Create a numpy array
+ Display array
+ Display type of array
+ Display size of array

In [4]:
import numpy as np

array = [[1,2,3],[4,5,6]]
nparray = np.array(array)
print(nparray)
print(type(nparray))
print(nparray.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


### Pytorch Tensor initialization

+ Create a torch.Tensor from array
+ Display Tensor
+ Display type of Tensor
+ Display size of Tensor

In [5]:
import torch

tensor_arr = torch.Tensor(array)
print(tensor_arr)
print(tensor_arr.type)
print(tensor_arr.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
<built-in method type of Tensor object at 0x0000020977D6DBD0>
torch.Size([2, 3])


### Identity array

In [6]:
print(np.ones((2,4)))

print(torch.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Random array

In [8]:
print(np.random.randn(2, 4))
print(np.random.rand(2, 4))

print(torch.randn((2,4)))
print(torch.rand((2,4)))

[[ 0.49757941  1.21899989 -1.97343286 -0.8883544 ]
 [-0.07033942  1.35262783 -1.1313371   0.89954977]]
[[0.52806885 0.69094027 0.68482042 0.77944977]
 [0.15156258 0.27967442 0.67937988 0.01698071]]
tensor([[-0.7756,  0.4732,  0.3204,  0.8793],
        [-0.3951,  0.0433,  1.3193,  0.3694]])
tensor([[0.9402, 0.2392, 0.4254, 0.0728],
        [0.8128, 0.7795, 0.9274, 0.3200]])


### Numpy array to Tensor and vice-versa

In [9]:
rand_arr = np.random.rand(2, 4)
print(rand_arr)
print(type(rand_arr))

np_to_tensor = torch.from_numpy(rand_arr)
print(np_to_tensor)
print(type(np_to_tensor))

tensor_to_np = np_to_tensor.numpy()
print(tensor_to_np)
print(type(tensor_to_np))

[[0.08688301 0.72823945 0.06910246 0.60743097]
 [0.9022125  0.65736611 0.68962442 0.15798959]]
<class 'numpy.ndarray'>
tensor([[0.0869, 0.7282, 0.0691, 0.6074],
        [0.9022, 0.6574, 0.6896, 0.1580]], dtype=torch.float64)
<class 'torch.Tensor'>
[[0.08688301 0.72823945 0.06910246 0.60743097]
 [0.9022125  0.65736611 0.68962442 0.15798959]]
<class 'numpy.ndarray'>


## Variables in pytorch

+ Difference b/w Tensor and Variables? Variables accumulates gradients. 
+ Variables are used for back propogation

In [11]:
from torch.autograd import Variable

var = Variable(torch.ones((3,3)), requires_grad = True)
print(var)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


### Basics of backward propogation

+ Let an equation be $y = x^2$
+ $X = [2, 4]$
+ Let recap o equation be $o = \frac{1}{2}\sum y = \frac{1}{2}\sum x^2$
+ Derivative of $o = x$ therefore, gradients $ = [2, 4]$

In [14]:
x = Variable(torch.Tensor([2, 4]), requires_grad = True)
y = x**2
print(y)

o = (1/2) * sum(y)
print(o)

o.backward() # Back Propogation

print('Gradients: {}'.format(x.grad))

tensor([ 4., 16.], grad_fn=<PowBackward0>)
tensor(10., grad_fn=<MulBackward0>)
Gradients: tensor([2., 4.])
